name: Dockerizing to Amazon ECR

on:
  push:
    branches:
      - main
      
jobs:
  publish:
    runs-on: ubuntu-latest
    
    env:
      AWS_REGION: ap-northeast-2
      ECR_REPOSITORY_NAME: hoony

    steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#         with:
#           distribution: 'corretto'
#           java-version: '17'
#           cache: gradle
  
      - name: Set up JDK 17
        uses: actions/checkout@v3
        with:
          java-version: 17
          cache: gradle       
          
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew         
      - name: build gradle
        run: ./gradlew clean assemble
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # Github Repository Secrets에 값 등록 필요!
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: ${{github.sha }}
        run: |
          CONTAINER_IMAGE_TEMP_PATH=$(mktemp -d)
          cp build/libs/*.jar ${CONTAINER_IMAGE_TEMP_PATH}
          docker build -f ./Dockerfile -t ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG} ${CONTAINER_IMAGE_TEMP_PATH}
          docker push ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}
